#!/usr/bin/env bash

check_network() {

  local ipaddr=""
  grepnet() {
    grep -oP "inet \K\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}"
  }

  if ifconfig tun0 > /dev/null 2>&1; then
    ipaddr=$(ifconfig tun0 2>/dev/null | grepnet)
    echo "󰆧 $ipaddr"
  elif ifconfig eth0 | grepnet >/dev/null 2>&1 ; then
    ipaddr=$(ifconfig eth0 2>/dev/null | grepnet )
    echo "󰈀 $ipaddr"
  else
    ipaddr=$(ifconfig wlan0 2>/dev/null || ifconfig wlan1 2>/dev/null | grepnet )
    if [[ -n "$ipaddr" ]];then
      echo "󰣺 On"
    else
        echo "󰣽 Off"
    fi
  fi

}   
check_network
